feat: use verified name on program certificate
edx/credentials pull request #1257
Opened 2021-08-10 16:51 UTC by alangsto

[MST-895](https://openedx.atlassian.net/browse/MST-895)

If user has chosen to use their verified name on certificates, use the verified name when rendering a program certificate.

2021-08-10 17:54 UTC, bseverino approved these changes

2021-08-10 18:19 UTC, tuchfarber requested changes

2021-08-10 18:19 UTC, tuchfarber commented on credentials/apps/core/models.py
> +                    raise e
I don't think I want all certs to fail if there's a bug in the name affirmation API. Can we either:
1. Fall back to using the normal name if there's an API issue, or
2. Put this behind a setting (we can default it on) that we can remote-config off if there's an issue.

2021-08-10 18:41 UTC, alangsto commented on credentials/apps/core/models.py
> +                    raise e
@tuchfarber, thanks for calling that out! I've updated the code so that we fall back to using the profile name if there is an API issue.

2021-08-11 00:20 UTC, tuchfarber approved these changes
Thanks for the fix!

2021-08-11 12:22 UTC, merged