[docs] Add documentation for LMS_USER_ID usage
edx/credentials pull request #1362
Opened 2021-09-27 16:31 UTC by Tj-Tracy

2021-09-27 20:18 UTC, oliviaruizknott approved these changes
I’ve not been following this work, but this looks good to me. It was easy to follow and didn’t leave any glaring questions.

2021-09-28 12:10 UTC, justinhynes commented on docs/lms_user_id.rst
> +Although credentials now supports **LMS_USER_ID**, it is not currently being widely used within the service. If the data is missing from a user, there should be no issues for general operation of the
This isn't true. This is one of the things we learned too late.

We require `lms_user_id` when sending emails to learners through ACE using the _Braze_ channel. However, Credentials is using the _django_email_ channel, and doesn't require the `lms_user_id` (just the email).

2021-09-28 12:11 UTC, justinhynes requested changes
I have one tiny change requested to make sure the information is valid. Thanks, TJ!

2021-09-28 13:17 UTC, oliviaruizknott commented on docs/lms_user_id.rst
> +Although credentials now supports **LMS_USER_ID**, it is not currently being widely used within the service. If the data is missing from a user, there should be no issues for general operation of the
Geez! Glad you also reviewed this, Justin. 😅

2021-09-28 13:36 UTC, Tj-Tracy commented on docs/lms_user_id.rst
> +Although credentials now supports **LMS_USER_ID**, it is not currently being widely used within the service. If the data is missing from a user, there should be no issues for general operation of the
good call. deleting it.

2021-09-28 13:59 UTC, justinhynes approved these changes

2021-09-28 14:10 UTC, merged